# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fiscal Year 2019 Budget
email: digital@boston.gov
description: >
  Beginning July 1, 2018 and ending June 30, 2019
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://budget.boston.gov"
twitter_username: CityOfBoston
github_username:  CityOfBoston

# Set source for Travis build
fy_source: fy19_adopted

# Collection settings
collections:
  cabinets:
    output: true
    permalink: "/operating-budget/:collection/:path/"
  departments:
    output: true
    permalink: "/operating-budget/cabinets/:path/"
  programs:
    output: true
    permalink: "/operating-budget/cabinets/:path/"
  categories:
    output: true
    permalink: "/capital-projects/:path/"
  cp_depts:
    output: true
    permalink: "/capital-projects/:path/"
  projects:
    output: true
    permalink: "/capital-projects/:path/"
  chapters:
    output: true
    permalink: "/:path/"

# Build settings
markdown: kramdown

exclude: [node_modules, package.json, Gulpfile, Gemfile, Gemfile.lock, vendor]
keep_files: [assets]
permalink: '/:collection/:title/'

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: "" # empty string for all files
      type: "cabinets"
    values:
      layout: "cabinets"
  - scope:
      path: "" # empty string for all files
      type: "departments"
    values:
      layout: "departments"
  - scope:
      path: "" # empty string for all files
      type: "programs"
    values:
      layout: "programs"
  - scope:
      path: "" # empty string for all files
      type: "categories"
    values:
      layout: "categories"
  - scope:
      path: "" # empty string for all files
      type: "cp_depts"
    values:
      layout: "cp_depts"
  - scope:
      path: "" # empty string for all files
      type: "projects"
    values:
      layout: "projects"
  - scope:
      path: "" # empty string for all files
      type: "chapters"
    values:
      layout: "bos_content"

mini_magick:
  thumbnail:
    source: img
    destination: img/cards
    resize: "385x160^"
    gravity: "center"
    extent: "385x160"

test:
  post:
    - rake test

include: ['_pages']
